export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_STOCKS_PENDING = 'REQUEST_STOCKS_PENDING';
export const REQUEST_STOCKS_SUCCESS = 'REQUEST_STOCKS_SUCCESS';
export const REQUEST_STOCKS_FAILED = 'REQUEST_STOCKS_FAILED';